[package]
name = "actix-server"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1.0.210", features = [
    "derive",
    "serde_derive",
    "alloc",
    "rc",
] }
tokio = { version = "1", features = ["full"] }
